#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec syncpack fix-mismatches || exit 1
pnpm exec syncpack set-semver-ranges || exit 1
pnpm exec syncpack format || exit 1

pnpm install

pnpm exec ls-lint || exit 1
pnpm exec lint-staged || exit 1
pnpm run typecheck || exit 1
pnpm run build || exit 1

git add \
  package.json \
  pnpm-lock.yaml \
  lib/cjs
